name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  NODE_ENV: nonlive

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      !startsWith(github.event.head_commit.message, 'Initial commit') && 
      !startsWith(github.event.head_commit.message, '🤖') &&
      !contains(github.event.head_commit.message, '[skip ci]')
    env:
      GH_APP_URL: ${{ vars.GH_APP_URL }}
      GH_APP_ID: ${{ vars.GH_APP_ID }}
      GH_CLIENT_ID: ${{ vars.GH_CLIENT_ID }}
      GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }}
      GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
      GH_WEBHOOK_SECRET: ${{ secrets.GH_WEBHOOK_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: yarn

      - name: Install Dependencies
        run: yarn

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy
        run: yarn deploy --stage $NODE_ENV

      - name: Output Serverless Info
        run: |
          echo "\`\`\`\n$(yarn -s summary --stage $NODE_ENV)\n\`\`\`" >> $GITHUB_STEP_SUMMARY
